version: 2
jobs:
  build:
    working_directory: ~/influxdb-builder
    docker:
      - image: circleci/node:6.11.1
      - image: influxdb:1.2.4-alpine
    steps:
      - checkout
      - run: npm prune
      - run: npm install
      - run: npm run ci

      - run: sudo npm install -g bunyan
      - run: bin/influxdb-builder --influxUrl http://localhost:8086 --database test --definition example/resources.yml --apply | bunyan
